### ISSUE TITLE
Initial `docker-compose up` always fails

### ISSUE THREAD

**Issue by talos** [GovLab/noi2#23]
The first time `docker-compose up` is run does not wait for postgres to initialize, and fails.  Subsequent runs will use the existing postgres container and don't fail.  We should always wait for postgres to be ready before launching the app.

**Comment by talos** [comment]
This is the output you would see from `docker-compose up` when this happens:

```
app_1 | /usr/local/lib/python2.7/dist-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
app_1 |   warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
app_1 | /bin/sh: 1: ../symlink-hooks.sh: not found
app_1 | Traceback (most recent call last):
app_1 |   File "/noi/manage.py", line 222, in <module>
app_1 |     manager.run()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
app_1 |     result = self.handle(sys.argv[0], sys.argv[1:])
app_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
app_1 |     res = handle(*args, **config)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
app_1 |     return self.run(*args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 195, in upgrade
app_1 |     command.upgrade(config, revision, sql=sql, tag=tag)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 165, in upgrade
app_1 |     script.run_env()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/alembic/script.py", line 390, in run_env
app_1 |     util.load_python_file(self.dir, 'env.py')
app_1 |   File "/usr/local/lib/python2.7/dist-packages/alembic/util.py", line 244, in load_python_file
app_1 |     module = load_module_py(module_id, path)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/alembic/compat.py", line 79, in load_module_py
app_1 |     mod = imp.load_source(module_id, path, fp)
app_1 |   File "migrations/env.py", line 73, in <module>
app_1 |     run_migrations_online()
app_1 |   File "migrations/env.py", line 59, in run_migrations_online
app_1 |     connection = engine.connect()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2018, in connect
app_1 |     return self._connection_cls(self, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 72, in __init__
app_1 |     if connection is not None else engine.raw_connection()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
app_1 |     self.pool.unique_connection, _connection)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
app_1 |     e, dialect, self)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
app_1 |     exc_info
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
app_1 |     reraise(type(exception), exception, tb=exc_tb)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
app_1 |     return fn()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 318, in unique_connection
app_1 |     return _ConnectionFairy._checkout(self)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
app_1 |     fairy = _ConnectionRecord.checkout(pool)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
app_1 |     rec = pool._do_get()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1151, in _do_get
app_1 |     return self._create_connection()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
app_1 |     return _ConnectionRecord(self)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
app_1 |     self.connection = self.__connect()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
app_1 |     connection = self.__pool._invoke_creator(self)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
app_1 |     return dialect.connect(*cargs, **cparams)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
app_1 |     return self.dbapi.connect(*cargs, **cparams)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
app_1 |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
app_1 | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
app_1 |         Is the server running on host "db" (172.17.6.43) and accepting
app_1 |         TCP/IP connections on port 5432?
app_1 | 
```

**Comment by toolness** [comment]
Oof, will this make our Travis CI integration a bit unpredictable as well?

**Comment by talos** [comment]
Yes, I imagine it could.

**Comment by talos** [comment]
@toolness I'm working on this BTW.
