### ISSUE TITLE
test_user_profiles_require_login is failing

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#33]
Our build seems to be busted as of 0d52d9ae1bdc9b20acdd2c089b9c9a8a76d96492 with the following traceback:

```
======================================================================
FAIL: test_user_profiles_require_login (app.tests.test_views.ViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/noi/app/tests/test_views.py", line 144, in test_user_profiles_require_login
    '/login?next=%2Fuser%2F1234')
  File "/usr/local/lib/python2.7/dist-packages/flask_testing/utils.py", line 213, in assertRedirects
    self.assertTrue(response.status_code in (301, 302))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
app.factory: WARNING: No NOI_DEPLOY found in config, deploy-specific attributes like the About page, custom domains and logos will be missing.
app.factory: WARNING: No MAIL_SERVER found in config, password reset will not work.
app.factory: WARNING: No GA_TRACKING_CODE found in config, analytics will not work.
app.factory: ERROR: Exception on /user/1234 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 85, in dumps
    return json.dumps(_tag(value), separators=(',', ':'))
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: lu'Please log in to access this page.' is not JSON serializable
```

**Comment by toolness** [comment]
I think this might be happening because a "lazy proxy" from `lazy_gettext` is being passed to flask-login's call to `flash()`, which the session JSON serializer is then confused by.

It seems like flask-login has its own [funky l10n mechanism](https://flask-login.readthedocs.org/en/latest/#localization) which we might have to use instead of (or in addition to) `lazy_gettext`, but I'm not sure.
