### ISSUE TITLE
ObjectDeletedError: Instance '<UserJoinedEvent at 0x7fef062dfa10>' has been deleted, or its row is otherwise not present.

### ISSUE THREAD

**Issue by mocxd** [GovLab/noi2#370]
Exception on /activity/page/9 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/noi/app/views.py", line 740, in activity_page
    events=get_latest_events(pageid))
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/noi/app/templates/_activity_events.html", line 19, in top-level template code
    {{ user_avatar(event.user) }}
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 511, in _load_for_state
    passive
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 547, in _get_ident_for_use_get
    for pk in self.mapper.primary_key
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2455, in _get_state_attr_by_column
    return state.manager[prop.key].impl.get(state, dict_, passive=passive)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 573, in get
    value = state._load_expired(state, passive)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 480, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 669, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
ObjectDeletedError: Instance '<UserJoinedEvent at 0x7fef062dfa10>' has been deleted, or its row is otherwise not present.

**Comment by mocxd** [comment]
did you see any more of these emails @naffis ? i haven't seen anything pop for a week or two

**Comment by naffis** [comment]
I haven't seen any recently @mocxd

**Comment by mocxd** [comment]
should we keep monitoring this?

**Comment by mocxd** [comment]
ok just got another one of these this morning

ObjectDeletedError: Instance '<UserJoinedEvent at 0x7f8545b7ea50>' has been deleted, or its row is otherwise not present.

any idea ?
